on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  releases-matrix:
    name: publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: ["arm", amd64]
        exclude:
          - goarch: "arm"
            goos: darwin
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: wangyoucao577/go-release-action@v1.18
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd"
          binary_name: "remote"
          extra_files: README.md
          ldflags: "-X main.version=${RELEASE_VERSION}"
